workflows:
  android-workflow:
    name: Android APK Debug
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd cancionero_app
          flutter pub get
      - name: Build APK
        script: |
          cd cancionero_app
          flutter build apk --debug
      - name: Copy APK
        script: |
          find /Users/builder/clone/cancionero_app/build -name "*.apk" -exec cp {} /Users/builder/clone/cancionero_app/app-debug.apk \;
    artifacts:
      - cancionero_app/**/*.apk
      - cancionero_app/app-debug.apk
